steps:
- name: gcr.io/cloud-builders/mvn
  args: ["spotless:check", "verify"]
  volumes:
  - name: user.home
    path: /root

- name: gcr.io/cloud-builders/mvn
  args: ["clean", "compile", "jib:build", "-Dimage=${_IMAGE}:$COMMIT_SHA"]
  volumes:
  - name: user.home
    path: /root

- name: gcr.io/cloud-builders/gcloud
  args: ["run", "deploy", "$_SERVICE_NAME", "--image=${_IMAGE}:$COMMIT_SHA", "--region", "$_DEPLOY_REGION", "--platform", "$_PLATFORM", "--allow-unauthenticated"]
