steps:
  - name: gcr.io/cloud-builders/mvn
    args: ["clean", "spotless:check", "verify", "jib:build", "-Djib.to.tags=$COMMIT_SHA"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["run", "deploy", "$_SERVICE_NAME", "--image=${_IMAGE}:$COMMIT_SHA", "--region", "$_DEPLOY_REGION", "--platform", "$_PLATFORM", "--allow-unauthenticated"]
