steps:
- name: gcr.io/cloud-builders/mvn
  args: ["-B", "spotless:check"]
  volumes:
  - name: user.home
    path: /root

- name: gcr.io/cloud-builders/mvn
  args: ["-B", "verify"]
  volumes:
  - name: user.home
    path: /root

- name: gcr.io/cloud-builders/mvn
  args: ["-B", "clean", "compile", "jib:build", "-Dimage=${_IMAGE}:$COMMIT_SHA"]
  volumes:
  - name: user.home
    path: /root

- name: gcr.io/google.com/cloudsdktool/cloud-sdk:367.0.0-alpine
  entrypoint: gcloud
  args: [
    "run", 
    "deploy", 
    "$_SERVICE_NAME", 
    "--image=${_IMAGE}:$COMMIT_SHA", 
    "--region=$_DEPLOY_REGION", 
    "--platform=$_PLATFORM", 
    "--allow-unauthenticated", 
    "--ingress=all", 
    "--concurrency=80",
    "--cpu=1",
    "--memory=512Mi",
    "--min-instances=0",
    "--use-http2",
    "--set-env-vars",
    "JAVA_TOOL_OPTIONS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1",
    "--set-cloudsql-instances="
    ]
