steps:
  - name: gcr.io/cloud-builders/mvn
    args: ["spotless:check", "install", "jib:build", "-Djib.to.tags=$COMMIT_SHA"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["run", "deploy", "cubicfox-attandance", "--image=europe-north1-docker.pkg.dev/cubicfox-attendance/cubicfox-attandance/cubicfox-attandance:$COMMIT_SHA", "--region", "europe-north1", "--platform", "managed"]
