server:
  http2.enabled: true
  shutdown: graceful
  port: ${PORT:8080}
  error:
      whitelabel.enabled: false
      include-message: always
      include-binding-errors: always
      include-stacktrace: never
      include-exception: false
